# Generated by Django 5.2 on 2025-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
