# Generated by Django 5.2 on 2025-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverer_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='order',
            name='products_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
