# Generated by Django 5.2 on 2025-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
