# Generated by Django 5.2 on 2025-06-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryInstructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
