# Generated by Django 5.2 on 2025-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0002_remove_shop_owner_shopowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='shop',
            name='shopImage',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
