# Generated by Django 5.2 on 2025-06-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0004_notification_order_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deliverer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_emitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
