# Generated by Django 5.2 on 2025-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0004_alter_order_deliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(null=True),
        ),
    ]
