# Generated by Django 5.2 on 2025-06-30 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0005_notification_deliverer_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('entregado', 'Pedido entregado'), ('cancelado', 'Pedido cancelado'), ('aceptado', 'Pedido aceptado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
