# Generated by Django 5.2 on 2025-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0002_remove_shop_owner_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('customer', 'Cliente'), ('deliver', 'Repartidor'), ('seller', 'Vendedor')], default='customer', max_length=20),
        ),
    ]
