# Generated by Django 5.2 on 2025-06-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0006_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upuntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('customer', 'Cliente'), ('deliver', 'Repartidor'), ('seller', 'Vendedor')], max_length=20),
        ),
    ]
