# Generated by Django 5.2 on 2025-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0007_alter_notification_deliverer_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
