# Generated by Django 5.2 on 2025-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0008_order_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
