# Generated by Django 5.2 on 2025-06-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0002_order_deliverer_paid_order_delivery_fee_and_more'),
        ('urappiapp', '0002_order_deliveryinstructions'),
        ('urappiapp', '0009_shop_votes_user_rating_user_votes'),
    ]

    operations = [
    ]
