# Generated by Django 5.2 on 2025-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0010_merge_20250630_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
