# Generated by Django 5.2 on 2025-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0011_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
