# Generated by Django 5.2 on 2025-07-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urappiapp', '0010_merge_20250630_1823'),
        ('urappiapp', '0012_alter_notification_id'),
    ]

    operations = [
    ]
